### ISSUE TITLE
Problem z bazą danych

### ISSUE THREAD

**Issue by ThePronixowy** [mic0ishere/mi-ads#1]
Cześć, mam problem z połączeniem się do bazy danych. Nie wiem gdzie znaleść Mongo_URL. Posiadam bazę danych MongoDB ale nie mogę się połączyć z nią. Posiadam takrze taki błąd

`(node:6504) UnhandledPromiseRejectionWarning: TypeError: bot.db.find(...).toArray is not a function
    at C:\Users\user\Desktop\E-Reklamy\index.js:42:44
    at C:\Users\user\Desktop\E-Reklamy\node_modules\mongoose\lib\helpers\promiseOrCallback.js:16:11
    at C:\Users\user\Desktop\E-Reklamy\node_modules\mongoose\lib\index.js:350:16
    at C:\Users\user\Desktop\E-Reklamy\node_modules\mongoose\lib\connection.js:867:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or
by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:6504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` Proszę o pomoc

**Comment by mic0ishere** [comment]
MONGO_URL to link do twojej bazy danych - [Dokumentacja](https://docs.mongodb.com/manual/reference/connection-string/).

**Comment by ThePronixowy** [comment]
a możesz dać przykład jakiś? Z byle jaką nazwą i ip i portem i hasłem? XD Bo prubowałem to i niedziało mi :/

**Comment by mic0ishere** [comment]
`mongodb://<username>:<password>@<url>/<database>?authSource=admin`

**Comment by ThePronixowy** [comment]
`mongodb://<..._ebot>:<costam>@<CO TU MA BYĆ?>/<CO TU MA BYĆ?>?authSource=admin`

**Comment by mafineeek** [comment]
XDDDDDDDDDD
